spring:
  application:
    name: product-management
  data:
    mongodb:
      uri: mongodb://dev:dev@localhost:27017/ProductManagement
      database: ProductManagement
#      uuid-representation: standard
#org:
#  springframework:
#    boot:
#      logging:
#        LoggingSystem: none
#logging:
#  LoggingSystem: none
#  level:
#    root: INFO
#    org.hibernate.SQL: INFO
#  config: logback-spring.xml
aws:
  s3:
    region: ap-southeast-1
    bucket-video: product-video-streaming
    timeout-download: 30
    timeout-upload: 30


server:
  port: 8100

