spring:
  application:
    name: product-management
  data:
    mongodb:
      uri: mongodb://dev:dev@localhost:27017/ProductManagement
      database: ProductManagement
#      uuid-representation: standard
#org:
#  springframework:
#    boot:
#      logging:
#        LoggingSystem: none
#logging:
#  LoggingSystem: none
#  level:
#    root: INFO
#    org.hibernate.SQL: INFO
#  config: logback-spring.xml

server:
  port: 8100

